baseURL = "https://doukutsu-rs.github.io/"
languageCode = "en-us"
theme = "drs"
title = "doukutsu-rs"
#googleAnalytics = "UA-XXXXXXXXX-X"
copyright = "© 2020-2021 doukutsu-rs contributors"
description = "A Rust reimplementation of Cave Story."

[taxonomies]
category = "categories"
series = "series"
tag = "tags"

[params]

[Permalinks]
post = "post/:slug"

[[params.downloads_nightly]]
platform = "Windows x64"
appveyor_job_name = "windows-x64"
english_link = "https://ci.appveyor.com/api/projects/alula/doukutsu-rs/artifacts/doukutsu-rs_win64.zip?branch=master&job=windows-x64https://ci.appveyor.com/api/projects/alula/doukutsu-rs/artifacts/doukutsu-rs_win64.zip?branch=master&job=windows-x64"

[[params.downloads_nightly]]
platform = "Linux x64"

[[params.downloads_nightly]]
platform = "Android ARM64"

[[params.downloads_nightly]]
platform = "macOS x64 (Intel Macs)"

[[params.downloads_nightly]]
platform = "macOS ARM64 (M1 Macs)"

[[params.menu]]
name = "blog"
url = "post/"

[[params.menu]]
name = "post series"
url = "series/"


[privacy]
[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true
