baseURL = "https://doukutsu-rs.github.io/"
languageCode = "en-us"
title = "doukutsu-rs"
copyright = "© 2020-2023 doukutsu-rs contributors"
description = "A Rust reimplementation of Cave Story."

disableKinds = ["taxonomy", "terms", "RSS"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
[[params.downloads_nightly]]
platform = "Windows x64"
appveyor_job_name = "windows-x64"
english_link = "https://ci.appveyor.com/api/projects/alula/doukutsu-rs/artifacts/doukutsu-rs_win64.zip?branch=master&job=windows-x64"

[[params.downloads_nightly]]
platform = "Linux x64"
appveyor_job_name = "linux-x64"
english_link = "https://ci.appveyor.com/api/projects/alula/doukutsu-rs/artifacts/doukutsu-rs_linux.zip?branch=master&job=linux-x64"

[[params.downloads_nightly]]
platform = "Android ARM64"

[[params.downloads_nightly]]
platform = "macOS x64 (Intel Macs)"
appveyor_job_name = "mac-x64"
english_link = "https://ci.appveyor.com/api/projects/alula/doukutsu-rs/artifacts/doukutsu-rs_mac-intel.zip?branch=master&job=mac-x64"

[[params.downloads_nightly]]
platform = "macOS ARM64 (M1 Macs)"
appveyor_job_name = "mac-arm64"
english_link = "https://ci.appveyor.com/api/projects/alula/doukutsu-rs/artifacts/doukutsu-rs_mac-m1.zip?branch=master&job=mac-arm64"


[privacy]
[privacy.googleAnalytics]
anonymizeIP = true
respectDoNotTrack = true
useSessionStorage = true
[privacy.twitter]
enableDNT = true
[privacy.youtube]
privacyEnhanced = true
